Add CI with pyam install

diff --git a/.github/workflows/ci-cd-workflow.yml b/.github/workflows/ci-cd-workflow.yml
--- a/.github/workflows/ci-cd-workflow.yml
+++ b/.github/workflows/ci-cd-workflow.yml
@@ -149,6 +149,37 @@ jobs:
               exit 1
           fi
 
+  build-pyam:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: [3.7]
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+      - name: Setup python
+        uses: actions/setup-python@v1
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install test dependencies
+        run: |
+          pip install --upgrade pip wheel
+          pip install -e .[tests]
+          pip install pyam-iamc
+
+      - name: Test with pytest
+        env:
+          MIN_COVERAGE: 90
+        run: |
+          pytest tests -r a --cov=scmdata --cov-report=xml
+          if ! coverage report --fail-under=${MIN_COVERAGE} --show-missing
+          then
+              echo
+              echo "Error: Test coverage has to be at least ${MIN_COVERAGE}"
+              exit 1
+          fi
+
   test-notebooks:
     runs-on: ubuntu-latest
     strategy:
